# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ecommerce' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GoogleSignIn'
  
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  
  pod 'FacebookLogin'
  
  # Pods for ecommerce

  target 'ecommerceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ecommerceUITests' do
    # Pods for testing
  end

end
